### ISSUE TITLE
nucleo-64 error on loading

### ISSUE THREAD

**Issue by zfranco55** [nopnop2002/STM32_TFT_8bit#7]
I have a core-64 stm32f103rb card, but in loading it gives me the error:
/home/user/Arduino/libraries/STM32_TFT_8bit-master/STM32_TFT_8bit.cpp:23:26: fatal error: libmaple / dma.h: No such file or directory
 #include <libmaple / dma.h>
how can i fix it?

**Comment by nopnop2002** [comment]
Requires core library

https://github.com/rogerclarkmelbourne/Arduino_STM32

If you use  Arduino_Core_STM32, please use this.

https://github.com/nopnop2002/Arduino-STM32-8bitTFT
